[tox]
envlist = py39, py310, py311, py312, py313, py314, flake8
skip_missing_interpreters = true

[testenv:flake8]
basepython = python
deps = flake8
skip_install = true
commands = flake8 tomita pysynth tests

[testenv]
deps =
    pytest>=7
commands =
    pytest --basetemp="{envtmpdir}" {posargs}

